# Generated by Django 3.2.3 on 2021-05-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
